version: "2"

services:
    service:
        container_name: server
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - db
        links:
            - db
        environment:
            PORT: 8080
            NODE_ENV: dev
            LOGGER_LEVEL: info
            REDIS_URL: redis://loclhost:6379 
    db:
        image: redis:6.2-alpine
        restart: always
        ports:
        - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes: 
        - db:/data
volumes:
    db:
        driver: local
